version: "3"

services:
  db:
    image: postgres:alpine
    container_name: ecoleta_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  server:
    container_name: ecoleta_server
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3333:3333"
    volumes:
      - ./server:/usr/app
    command: sh -c "npm run knex:migrate && npm run dev"

  web:
    container_name: ecoleta_web
    stdin_open: true
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - "3000:3000"
    volumes:
      - ./web:/usr/app
    command: npm start