version: "3"

services:
  server:
    container_name: ecoleta_server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - ./server:/usr/app
    command: npm run dev
  web:
    container_name: ecoleta_web
    stdin_open: true
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web:/usr/app
    command: npm start